# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install NPM Packages
      - name: Install NPM Packages
        run: npm install
        
      # Build for production
      - name: Build for production
        run: npm run build
        
      # Push to backend repo
      - name: Push to backend repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: dist
          target-directory: output/
          destination-github-username: 'GDSCWallet'
          destination-repository-name: 'GDSC_wallet_backend'
          user-email: ${{ secrets.USER_EMAIL }}
          commit-message: Auto Deploy
          target-branch: test
          
